sudo: required
services:
  - docker

before_install:
  - docker build -t bleibig/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run bleibig/react-test npm run test -- --coverage

after_success:
  - docker build -t bleibig/multi-client ./client
  - docker build -t bleibig/multi-server ./server
  - docker build -t bleibig/multi-nginx ./nginx
  - docker build -t bleibig/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bleibig/multi-client
  - docker push bleibig/multi-server
  - docker push bleibig/multi-nginx
  - docker push bleibig/multi-worker
